set search_path to public, extensions;

create table if not exists curator_conversations (
  tenant_id       uuid not null
, id              uuid not null default gen_random_uuid()
, user_id         text not null
, label           text not null default 'New conversation'
, messages        jsonb not null default '[]'
, document_ids    jsonb not null default '[]'
, feature_states  jsonb not null default '[]'
, scope           text not null default 'all'
, created_at      bigint not null
, updated_at      bigint not null
, primary key (tenant_id, id)
) partition by list (tenant_id);

create index if not exists idx_curator_conversations_user
  on curator_conversations (tenant_id, user_id, updated_at desc);

comment on table curator_conversations is
'Curator (RAG chat) conversation history per user.
- tenant_id: partition key (composite PK), uuid
- scope: access group id or ''all'' (sentinel — no group filtering)
- messages/document_ids/feature_states: jsonb arrays, full replacement on update
- Timestamps are epoch milliseconds';

comment on column curator_conversations.tenant_id is 'Partition key. Identifies the owning tenant (UUID).';
comment on column curator_conversations.id is 'Conversation UUID, generated by the store layer.';
comment on column curator_conversations.user_id is 'Opaque user identity (e.g. Supabase auth UID).';
comment on column curator_conversations.label is 'Display name. LLM-generated on creation, user-editable.';
comment on column curator_conversations.messages is 'Ordered array of CuratorMessage objects (jsonb). Full replacement on update.';
comment on column curator_conversations.document_ids is 'Array of document IDs referenced in this conversation. IDs only — content not stored.';
comment on column curator_conversations.feature_states is 'Snapshot of feature toggle states at time of last update.';
comment on column curator_conversations.scope is 'Access group ID used to filter documents, or ''all'' for no filtering.';
comment on column curator_conversations.created_at is 'Creation timestamp, epoch milliseconds.';
comment on column curator_conversations.updated_at is 'Last update timestamp, epoch milliseconds. Used for sort order.';
