set search_path to public, extensions;

create table if not exists plans (
  tenant_id    uuid not null
, id           uuid not null default gen_random_uuid()
, goal         text not null
, instructions text
, config       jsonb
, status       text not null default 'pending'
    check (status in ('pending', 'running', 'completed', 'failed', 'cancelled'))
, created_at   bigint not null
, completed_at bigint
, duration_ms  bigint
, primary key (tenant_id, id)
) partition by list (tenant_id);

create index if not exists idx_plans_status     on plans(status);
create index if not exists idx_plans_created_at on plans(tenant_id, created_at desc);

comment on table plans is
'Plan-driven execution plans generated by the agent planner.
- tenant_id: new column, partition key
- goal/instructions/config make the plan self-describing
- Task counts computed from planned_tasks
- Status transitions: pending → running → completed | failed | cancelled
- Timestamps are epoch milliseconds';
