fn main() {
  // When the e2e-testing feature is active, generate a capabilities file that
  // grants the playwright plugin's pw_result IPC permission so the eval callback
  // can reach the Rust side. The file is removed on non-e2e builds so it doesn't
  // pollute production capability validation.
  #[cfg(feature = "e2e-testing")]
  {
    let e2e_cap = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "e2e-testing",
  "description": "Permissions for E2E Playwright testing — generated by build.rs",
  "windows": ["main"],
  "permissions": ["playwright:default"]
}"#;
    std::fs::write("capabilities/e2e-testing.json", e2e_cap)
      .expect("failed to write e2e-testing capabilities");
  }

  #[cfg(not(feature = "e2e-testing"))]
  {
    let _ = std::fs::remove_file("capabilities/e2e-testing.json");
  }

  tauri_build::build()
}
